# Generated by Django 4.1.4 on 2022-12-23 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('apelido', models.CharField(max_length=100)),
                ('observação', models.CharField(max_length=100)),
            ],
        ),
    ]
